package com.mycompany.gonzalezpereiraalbamaria_examenud2;


import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author alba gonzalez
 */
public class GonzalezAlba_Vuelos extends javax.swing.JFrame {

    /**
     * Creates new form GonzalezAlba_Vuelos
     */
    public GonzalezAlba_Vuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpReservas = new javax.swing.JPanel();
        jlReserva = new javax.swing.JLabel();
        jlDatosVuelo = new javax.swing.JLabel();
        jtxOrigen = new javax.swing.JLabel();
        jlDestino = new javax.swing.JLabel();
        jcbOrigen = new javax.swing.JComboBox<>();
        jcbDestino = new javax.swing.JComboBox<>();
        jbOrigen = new javax.swing.JButton();
        jbDestino = new javax.swing.JButton();
        jlDatos = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jlApellidos = new javax.swing.JLabel();
        jtxApellidos = new javax.swing.JTextField();
        jlDireccion = new javax.swing.JLabel();
        jtxDireccion = new javax.swing.JTextField();
        jlLocalidad = new javax.swing.JLabel();
        jtxLocalidad = new javax.swing.JTextField();
        jlfechaReserva = new javax.swing.JLabel();
        jcbDia = new javax.swing.JComboBox<>();
        jcbMes = new javax.swing.JComboBox<>();
        jcbAno = new javax.swing.JComboBox<>();
        jbConfirmar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jmenu = new javax.swing.JMenuBar();
        jmVuelos = new javax.swing.JMenu();
        jmiNuevoV = new javax.swing.JMenuItem();
        jmiEliminarV = new javax.swing.JMenuItem();
        jmiMostrarV = new javax.swing.JMenuItem();
        jmOpciones = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlReserva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlReserva.setText("Reserva de vuelos");

        jlDatosVuelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlDatosVuelo.setText("Datos del vuelo");

        jtxOrigen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtxOrigen.setText("Origen");

        jlDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlDestino.setText("Destino");

        jcbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigo", "Madrid", "Oporto", "Barcelona", "Valencia", "Málaga", "Granada" }));

        jcbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigo", "Madrid", "Oporto", "Barcelona", "Valencia", "Málaga", "Granada" }));

        jbOrigen.setBackground(new java.awt.Color(51, 51, 255));
        jbOrigen.setForeground(new java.awt.Color(255, 255, 255));
        jbOrigen.setText("Mostrar origen");
        jbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOrigenActionPerformed(evt);
            }
        });

        jbDestino.setBackground(new java.awt.Color(51, 51, 255));
        jbDestino.setForeground(new java.awt.Color(255, 255, 255));
        jbDestino.setText("Mostrar destino");
        jbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDestinoActionPerformed(evt);
            }
        });

        jlDatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlDatos.setText("Datos de la reserva");

        jlNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlNombre.setText("Nombre");

        jlApellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlApellidos.setText("Apellidos");

        jlDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlDireccion.setText("Dirección");

        jlLocalidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlLocalidad.setText("Localidad");

        jlfechaReserva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlfechaReserva.setText("Fecha de reserva");

        jcbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jcbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026" }));

        jbConfirmar.setBackground(new java.awt.Color(51, 51, 255));
        jbConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirmar.setText("Confirmar datos");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jbCerrar.setBackground(new java.awt.Color(51, 51, 255));
        jbCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrar.setText("Cerrar ventana");
        jbCerrar.setActionCommand("");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpReservasLayout = new javax.swing.GroupLayout(jpReservas);
        jpReservas.setLayout(jpReservasLayout);
        jpReservasLayout.setHorizontalGroup(
            jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReservasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlDatosVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpReservasLayout.createSequentialGroup()
                            .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlDestino)
                                .addComponent(jlDatos)
                                .addComponent(jlNombre)
                                .addComponent(jlLocalidad)
                                .addComponent(jlfechaReserva))
                            .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpReservasLayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jpReservasLayout.createSequentialGroup()
                                            .addComponent(jcbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jbOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jpReservasLayout.createSequentialGroup()
                                            .addComponent(jcbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jbDestino))))
                                .addGroup(jpReservasLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtxLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jtxApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jpReservasLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(jcbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jlApellidos)
                        .addComponent(jlDireccion))
                    .addGroup(jpReservasLayout.createSequentialGroup()
                        .addComponent(jlReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGap(96, 96, 96))
            .addGroup(jpReservasLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jbConfirmar)
                .addGap(45, 45, 45)
                .addComponent(jbCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpReservasLayout.setVerticalGroup(
            jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReservasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlDatosVuelo)
                .addGap(18, 18, 18)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxOrigen)
                    .addComponent(jcbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOrigen))
                .addGap(15, 15, 15)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDestino)
                    .addComponent(jcbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDestino))
                .addGap(34, 34, 34)
                .addComponent(jlDatos)
                .addGap(18, 18, 18)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellidos)
                    .addComponent(jtxApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDireccion)
                    .addComponent(jtxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLocalidad)
                    .addComponent(jtxLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlfechaReserva)
                    .addComponent(jcbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jpReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirmar)
                    .addComponent(jbCerrar))
                .addGap(16, 16, 16))
        );

        jmVuelos.setText("Vuelos");

        jmiNuevoV.setText("Nuevo Vuelo");
        jmiNuevoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoVActionPerformed(evt);
            }
        });
        jmVuelos.add(jmiNuevoV);

        jmiEliminarV.setText("Eliminar Vuelos");
        jmVuelos.add(jmiEliminarV);

        jmiMostrarV.setText("Mostrar Vuelos");
        jmiMostrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarVActionPerformed(evt);
            }
        });
        jmVuelos.add(jmiMostrarV);

        jmenu.add(jmVuelos);

        jmOpciones.setText("Opciones");

        jmiSalir.setText("Salir");
        jmOpciones.add(jmiSalir);

        jmenu.add(jmOpciones);

        setJMenuBar(jmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        String origen = jcbOrigen.getSelectedItem().toString();
        String destino = jcbDestino.getSelectedItem().toString();
        String usuario = jtxNombre.getText() + " " + jtxApellidos.getText();
        String fecha = jcbDia.getSelectedItem().toString() + " de " + jcbMes.getSelectedItem().toString() + " de " + jcbAno.getSelectedItem().toString();
        System.out.println(fecha);

        int opcion = JOptionPane.showConfirmDialog(null, "Los datos del vuelo son: Origen->" + origen + " - Destino->" + destino + "\n"
                + "Los datos del usuario son: " + usuario + "\n"
                + "Los datos de la reserva: " + fecha, "Confirmación de la reserva", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Datos guardados", "Datos de la reserva", JOptionPane.INFORMATION_MESSAGE);
        }
        if (opcion == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Datos no guardados", "Datos de la reserva", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOrigenActionPerformed
        int origen = jcbOrigen.getSelectedIndex();
        String nombreOrigen = jcbOrigen.getItemAt(origen);
        JDialog dialogoModalOrigen = new JDialog(this, "Datos origen", true);
        dialogoModalOrigen.setLayout(new FlowLayout());
        dialogoModalOrigen.setSize(200, 100);
        JLabel titulo = new JLabel("Datos de origen: " + nombreOrigen);
        JButton aceptar = new JButton("Aceptar");
        aceptar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialogoModalOrigen.dispose();//cerramos ventana
            }
        });
        dialogoModalOrigen.add(titulo);
        dialogoModalOrigen.add(aceptar);
        dialogoModalOrigen.setLocationRelativeTo(this);
        dialogoModalOrigen.setVisible(true);
    }//GEN-LAST:event_jbOrigenActionPerformed

    private void jbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDestinoActionPerformed
        int destino = jcbDestino.getSelectedIndex();
        String nombreDestino = jcbDestino.getItemAt(destino);
        JDialog dialogoModalDestino = new JDialog(this, "Datos destino", true);
        dialogoModalDestino.setLayout(new FlowLayout());
        dialogoModalDestino.setSize(200, 100);
        JLabel titulo = new JLabel("Datos de destino: " + nombreDestino);
        JButton aceptar = new JButton("Aceptar");
        aceptar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialogoModalDestino.dispose();//cerramos ventana
            }
        });
        dialogoModalDestino.add(titulo);
        dialogoModalDestino.add(aceptar);
        dialogoModalDestino.setLocationRelativeTo(this);
        dialogoModalDestino.setVisible(true);
    }//GEN-LAST:event_jbDestinoActionPerformed

    private void jmiNuevoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoVActionPerformed
        
        JDialog dialogoNuevo = new JDialog(this, "Datos del nuevo vuelo");
        dialogoNuevo.setLayout(new GridLayout(3, 2));
        dialogoNuevo.setSize(400, 100);
        JLabel origen = new JLabel("Origen: ");
        JTextField txtOr = new JTextField(25);
        JLabel destino = new JLabel("Destino: ");
        JTextField txtDest = new JTextField(25);
        JButton guardar = new JButton("Guardar");
        JButton cancelar = new JButton("Cancelar");
        cancelar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialogoNuevo.dispose();//cerramos ventana
            }
        });
        dialogoNuevo.add(origen);
        dialogoNuevo.add(txtOr);
        dialogoNuevo.add(destino);
        dialogoNuevo.add(txtDest);
        dialogoNuevo.add(guardar);
        dialogoNuevo.add(cancelar);
        dialogoNuevo.setVisible(true);
    }//GEN-LAST:event_jmiNuevoVActionPerformed

    private void jmiMostrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarVActionPerformed
        JDialog dialogoMostrar = new JDialog(this, "Vuelos");
        dialogoMostrar.setLayout(new FlowLayout());
        dialogoMostrar.setSize(400, 100);
        ArrayList<String> vuelos = new ArrayList<>();
        vuelos.add("Vigo-Madrid");
        vuelos.add("Barcelona-Vigo");
        vuelos.add("Madrid-Barcelona");
        vuelos.add("Vigo-Málaga");
        JButton cerrar = new JButton("Cerrar ventana");
        cerrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialogoMostrar.dispose();//cerramos ventana
            }
        });
        for (String vuelo : vuelos) {
            dialogoMostrar.add(new JLabel(vuelo + ","));     
        }        
        dialogoMostrar.add(cerrar);
        dialogoMostrar.setVisible(true);
    }//GEN-LAST:event_jmiMostrarVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GonzalezAlba_Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GonzalezAlba_Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GonzalezAlba_Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GonzalezAlba_Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GonzalezAlba_Vuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbDestino;
    private javax.swing.JButton jbOrigen;
    private javax.swing.JComboBox<String> jcbAno;
    private javax.swing.JComboBox<String> jcbDestino;
    private javax.swing.JComboBox<String> jcbDia;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbOrigen;
    private javax.swing.JLabel jlApellidos;
    private javax.swing.JLabel jlDatos;
    private javax.swing.JLabel jlDatosVuelo;
    private javax.swing.JLabel jlDestino;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlLocalidad;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlReserva;
    private javax.swing.JLabel jlfechaReserva;
    private javax.swing.JMenu jmOpciones;
    private javax.swing.JMenu jmVuelos;
    private javax.swing.JMenuBar jmenu;
    private javax.swing.JMenuItem jmiEliminarV;
    private javax.swing.JMenuItem jmiMostrarV;
    private javax.swing.JMenuItem jmiNuevoV;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JPanel jpReservas;
    private javax.swing.JTextField jtxApellidos;
    private javax.swing.JTextField jtxDireccion;
    private javax.swing.JTextField jtxLocalidad;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JLabel jtxOrigen;
    // End of variables declaration//GEN-END:variables
}
