package com.mycompany.gonzalezpereiraalba_examenfinal;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author a24exame-dam-f
 */
public class AMGP_Farmacia extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public AMGP_Farmacia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFarmacia = new javax.swing.JPanel();
        jlFarmacia = new javax.swing.JLabel();
        jtxMedicamento = new javax.swing.JLabel();
        jlInsertar = new javax.swing.JLabel();
        jlProveedor = new javax.swing.JLabel();
        jlStock = new javax.swing.JLabel();
        jcbMedicamento = new javax.swing.JComboBox<>();
        jcbProveedor = new javax.swing.JComboBox<>();
        jbColor = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbConfirmar = new javax.swing.JButton();
        jbCargar = new javax.swing.JButton();
        jtxStock = new com.mycompany.gonzalezpereiraalba_examenfinal.TextFieldComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlFarmacia.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jlFarmacia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFarmacia.setText("Farmacia Teis");

        jtxMedicamento.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jtxMedicamento.setText("Medicamento");

        jlInsertar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlInsertar.setText("Insertar stock medicamento");

        jlProveedor.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jlProveedor.setText("Proveedor");

        jlStock.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jlStock.setText("Stock");

        jcbMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paracetamol", "Ibuprofeno", "Amoxicilina", "Atorvastatina", "Metformina" }));

        jcbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GlaxoSmithKline (GSK)", "Bayer", "Sandoz", "Pfizer", "Merck" }));

        jbColor.setBackground(new java.awt.Color(51, 153, 255));
        jbColor.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jbColor.setForeground(new java.awt.Color(255, 255, 255));
        jbColor.setText("Cambiar Color");
        jbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbColorActionPerformed(evt);
            }
        });

        jbConfirmar.setBackground(new java.awt.Color(51, 153, 255));
        jbConfirmar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jbConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirmar.setText("Confirmar datos");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jbCargar.setBackground(new java.awt.Color(51, 153, 255));
        jbCargar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jbCargar.setForeground(new java.awt.Color(255, 255, 255));
        jbCargar.setText("Cargar datos");
        jbCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarActionPerformed(evt);
            }
        });

        jtxStock.setCaretColor(new java.awt.Color(255, 255, 255));
        jtxStock.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpFarmaciaLayout = new javax.swing.GroupLayout(jpFarmacia);
        jpFarmacia.setLayout(jpFarmaciaLayout);
        jpFarmaciaLayout.setHorizontalGroup(
            jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFarmaciaLayout.createSequentialGroup()
                .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFarmaciaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpFarmaciaLayout.createSequentialGroup()
                                    .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(25, 25, 25)
                                    .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcbMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)))
                            .addGroup(jpFarmaciaLayout.createSequentialGroup()
                                .addComponent(jlStock, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jtxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jbColor))
                            .addGroup(jpFarmaciaLayout.createSequentialGroup()
                                .addComponent(jlInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(jpFarmaciaLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jbConfirmar)
                        .addGap(93, 93, 93)
                        .addComponent(jbCargar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFarmaciaLayout.setVerticalGroup(
            jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFarmaciaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlFarmacia)
                .addGap(27, 27, 27)
                .addComponent(jlInsertar)
                .addGap(23, 23, 23)
                .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxMedicamento)
                    .addComponent(jcbMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProveedor))
                .addGap(22, 22, 22)
                .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlStock)
                    .addComponent(jbColor)
                    .addComponent(jtxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirmar)
                    .addComponent(jbCargar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JFrame frame = this;
    /**
     * método que permite escoger un color y modifica el color del fondo del textField de stock
     * JColorChooser
     * @param evt 
     */
    private void jbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbColorActionPerformed
        JColorChooser colorChooser = new JColorChooser();

        // creamos los actionListener de JColorChooser
        ActionListener okListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Color colorSeleccionado = colorChooser.getColor();
                jtxStock.setBackground(colorSeleccionado);
            }
        };

        ActionListener okCancel = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Se ha cancelado escoger color");
            }
        };
        
        //Creamos el diálogo y visibilizamops
        JDialog dialogo = JColorChooser.createDialog(frame, "Elige un color", true, colorChooser, okListener, okCancel);
        dialogo.setVisible(true);


    }//GEN-LAST:event_jbColorActionPerformed

    /**
     * método que permite guardar los datos en un archivo - JFileChooser y ObjectOutputStream
     * @param evt 
     */
    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        File file = null;

        JFileChooser filechooser = new JFileChooser();
        int respuesta = filechooser.showSaveDialog(null);
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            file = filechooser.getSelectedFile();

            try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(file));) {
                String nombre = (String) jcbMedicamento.getSelectedItem();
                System.out.println("nombre = " + nombre);
                String proveedor = (String) jcbProveedor.getSelectedItem();
                String stock = jtxStock.getText();
                Data datoNuevo = new Data(nombre, proveedor, stock);
                //Data datoNuevo = new Data();
                datoNuevo.setStock(stock);
                System.out.println("Dato nuevo =" + datoNuevo);
               
                oos.writeObject(datoNuevo);

                jcbMedicamento.setSelectedIndex(0);
                jcbProveedor.setSelectedIndex(0);
                jtxStock.setText("");

            } catch (FileNotFoundException ex) {
                Logger.getLogger(AMGP_Farmacia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AMGP_Farmacia.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
           
//            JOptionPane panel = new JOptionPane("Cancelación");
//            panel.createDialog("Datos no guardados");
//            panel.setVisible(true);
            System.out.println("Datos no guardados");
        }

    }//GEN-LAST:event_jbConfirmarActionPerformed

    /**
     * método que permite leer los datos en un archivo - JFileChooser y ObjectInputStream
     * @param evt 
     */
    private void jbCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarActionPerformed
        File file = null;
        
        JFileChooser filechooser = new JFileChooser();
        int respuesta = filechooser.showOpenDialog(null);
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            file = filechooser.getSelectedFile();
            try(ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file));) {
                Data datosLeidos = (Data) ois.readObject();
                jcbMedicamento.setSelectedItem(datosLeidos.getMedicamento());
                jcbProveedor.setSelectedItem(datosLeidos.getProveedor());
                jtxStock.setText(datosLeidos.getStock());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AMGP_Farmacia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AMGP_Farmacia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AMGP_Farmacia.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbCargarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCargar;
    private javax.swing.JButton jbColor;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JComboBox<String> jcbMedicamento;
    private javax.swing.JComboBox<String> jcbProveedor;
    private javax.swing.JLabel jlFarmacia;
    private javax.swing.JLabel jlInsertar;
    private javax.swing.JLabel jlProveedor;
    private javax.swing.JLabel jlStock;
    private javax.swing.JPanel jpFarmacia;
    private javax.swing.JLabel jtxMedicamento;
    private com.mycompany.gonzalezpereiraalba_examenfinal.TextFieldComponent jtxStock;
    // End of variables declaration//GEN-END:variables
}
