
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author alba_
 */
public class NuevoLibro extends javax.swing.JFrame {

    //Declaro el array de libros:
    ArrayList<Libro> libros = new ArrayList<>();

    /**
     * Creates new form NuevoLibro
     */
    public NuevoLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        autores = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        editorial = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        novela = new javax.swing.JRadioButton();
        biblio = new javax.swing.JRadioButton();
        poesia = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valoracion = new javax.swing.JSpinner();
        botonAnhadir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BiblioTeis");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        titulo.setText("titulo");
        titulo.setToolTipText("Introduzca el título");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Título:");

        autores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja un autor:", "Juan Gómez-Jurado", "Rebecca Yarros", "Arturo Pérez-Reverte", "Carmen Mola", "Gloria Fuertes" }));
        autores.setToolTipText("Escoja el autor/a");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Autor:");

        editorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una editorial:", "Acantilado", "Aguilar", "Akal", "Alfaguara", "Alianza", "Anagrama" }));
        editorial.setToolTipText("Escoja la editorial");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Editorial:");

        buttonGroup1.add(novela);
        novela.setText("Novela");
        novela.setToolTipText("Novela");

        buttonGroup1.add(biblio);
        biblio.setText("Bibliográfico");
        biblio.setToolTipText("Bibliográfico");

        buttonGroup1.add(poesia);
        poesia.setText("Poesía");
        poesia.setToolTipText("Poesía");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tipo de libro:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Valoración:");

        valoracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        valoracion.setToolTipText("Escoja una valoración");

        botonAnhadir.setBackground(new java.awt.Color(204, 0, 255));
        botonAnhadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAnhadir.setText("Añadir libro");
        botonAnhadir.setToolTipText("Pulse el botón para enviar");
        botonAnhadir.setActionCommand("");
        botonAnhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnhadirActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Mostrar Libros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Borrar bibioteca");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 0, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Añadir autor");
        jButton3.setToolTipText("Añade un autor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonAnhadir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(valoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(novela, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(biblio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(poesia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novela)
                    .addComponent(biblio)
                    .addComponent(poesia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(valoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnhadir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 0, 153));

        jMenu1.setText("Inicio");

        jMenuItem1.setText("Reservar Libro");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Buscar");

        jMenuItem3.setText("Por autor");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Por título");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Por editorial");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnhadirActionPerformed
        //Creamos las variables que vamos a usar:
        ButtonModel seleccion = buttonGroup1.getSelection();
        int valor = (int) valoracion.getValue();
        Libro libro;
        String tipo;
        JDialog dialogoModal = new JDialog(this, "Error de validación", true);
        dialogoModal.setLayout(new FlowLayout());
        dialogoModal.setSize(200, 100);
        

        //cuando se da al botón añadir libro:
        if (titulo.getText().equals("")) {
            JLabel titulo = new JLabel("Debe introducir un título.");
            JButton aceptar = new JButton("Aceptar");
            aceptar.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialogoModal.dispose();//cerramos ventana
                }
            });
            dialogoModal.add(titulo);
            dialogoModal.add(aceptar);
            dialogoModal.setLocationRelativeTo(this);
            dialogoModal.setVisible(true);
            return;
        }

        // Si los autores está en el index 0 es que no se ha escogido ningún autor
        if (autores.getSelectedIndex() == 0) {
            JLabel autor = new JLabel("Debe escoger un autor.");
            JButton aceptar = new JButton("Aceptar");
            aceptar.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialogoModal.dispose();//cerramos ventana
                }
            });
            dialogoModal.add(autor);
            dialogoModal.add(aceptar);
            dialogoModal.setLocationRelativeTo(this);
            dialogoModal.setVisible(true);
            return;
        }

        //Si la editorial está en el index 0 es que no se ha escogido ninguna
        if (editorial.getSelectedIndex() == 0) {
            JLabel editorial = new JLabel("Debe escoger una editorial.");
            JButton aceptar = new JButton("Aceptar");
            aceptar.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialogoModal.dispose();//cerramos ventana
                }
            });
            dialogoModal.add(editorial);
            dialogoModal.add(aceptar);
            dialogoModal.setLocationRelativeTo(this);
            dialogoModal.setVisible(true);
            return;
        }

        // Comprobamos que se ha marcado algún radiobutton
        if (seleccion != novela.getModel() && seleccion != biblio.getModel() && seleccion != poesia.getModel()) {
            JLabel tipoLibro = new JLabel("Debe escoger un tipo de libro.");
            JButton aceptar = new JButton("Aceptar");
            aceptar.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialogoModal.dispose();//cerramos ventana
                }
            });
            dialogoModal.add(tipoLibro);
            dialogoModal.add(aceptar);
            dialogoModal.setLocationRelativeTo(this);
            dialogoModal.setVisible(true);
            return;
        }

        //comprobamos que el valor se ha escogido
        if (valor < 0 || valor > 5) {
            JLabel tipoLibro = new JLabel("Debe escoger un tipo de libro.");
            JButton aceptar = new JButton("Aceptar");
            aceptar.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialogoModal.dispose();//cerramos ventana
                }
            });
            dialogoModal.add(tipoLibro);
            dialogoModal.add(aceptar);
            dialogoModal.setLocationRelativeTo(this);
            dialogoModal.setVisible(true);
            return;
        }

        //Comprobamos qué tipo está seleccionado
        if (novela.isSelected()) {
            tipo = novela.getText();
        } else if (biblio.isSelected()) {
            tipo = biblio.getText();
        } else {
            tipo = poesia.getText();
        }

        //creamos el libro y lo añadimos al ArrayList
        libro = new Libro(titulo.getText(), (String) autores.getSelectedItem(), (String) editorial.getSelectedItem(), tipo, valor);
        libros.add(libro); // añadimos el arraylist

        //Comprobamos que sale el mensaje
        System.out.println("Libro añadido correctamente");
    }//GEN-LAST:event_botonAnhadirActionPerformed

    // método que muestra los libros de la biblioteca
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String listaLibros = "";
        for (Libro libro : libros) {
            listaLibros += libro + "\n";
        }

        JOptionPane.showMessageDialog(null, listaLibros, "Lista de Libros", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    //Evento que elimina todos los libros de la biblioteca
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        libros.clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Método que añade un autor con un diálogo no modal
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //creamos el diálogo no modal:
        JDialog dialogo = new JDialog(this, "Insertar autor");
        dialogo.setLayout(new FlowLayout());
        
        //creamos los elementos del diálogo
        JLabel nombreAutor = new JLabel("Introduce el nombre del autor:");
        JTextField autor = new JTextField(30);
        JButton aceptar = new JButton("Aceptar");
        JButton cancelar = new JButton("Cancelar");
        JFrame frame = this;
        
        //creamos los eventos de aceptar y cancelar
        cancelar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                dialogo.dispose();
            }
        });
        
        aceptar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JDialog dialogoAcept = new JDialog(frame, "Aceptar", true); //diálogo modal
                dialogoAcept.setLayout(new FlowLayout());
                JLabel confirm = new JLabel("¿Quiere añadir el autor a la lista?");
                JButton yes = new JButton("Sí");
                JButton no = new JButton("No");
                
                //creamos los eventos de los botones:
                yes.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        autores.addItem(autor.getText());//añadimos el autor a la lista de autores
                        autor.setText(""); //ponemos el texto en blanco
                        dialogoAcept.dispose();//cerramos el diálogo modal
                    }  
                });
                        
                no.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        dialogoAcept.dispose();
                    }
                });
                
                //añadimos los elementos al JDialog
                dialogoAcept.add(confirm);
                dialogoAcept.add(yes);
                dialogoAcept.add(no);
                
                //ponemos las medidas:
                dialogoAcept.setSize(200,100);
                dialogoAcept.setLocationRelativeTo(frame);
                dialogoAcept.setVisible(true);
               
            }
        });
        
        //agregamos los elementos
        dialogo.add(nombreAutor);
        dialogo.add(autor);
        dialogo.add(aceptar);
        dialogo.add(cancelar);
        
        //ponemos un tamaño, lugar
        dialogo.setSize(400, 150);
        dialogo.setLocationRelativeTo(this);
        
        //lo hacemos visible
        dialogo.setVisible(true);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> autores;
    private javax.swing.JRadioButton biblio;
    private javax.swing.JButton botonAnhadir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> editorial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton novela;
    private javax.swing.JRadioButton poesia;
    private javax.swing.JTextField titulo;
    private javax.swing.JSpinner valoracion;
    // End of variables declaration//GEN-END:variables
}
